apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-detector
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/component: detector
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.detector.ports.api }}
      targetPort: http
      protocol: TCP
    - name: prometheus
      port: {{ .Values.detector.ports.prometheus }}
      targetPort: prometheus
      protocol: TCP
  selector:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/component: detector
    app.kubernetes.io/instance: {{ .Release.Name }}
