apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | b64enc | quote }}
  REDIS_URL: {{ printf "redis://%s:%d" (ternary .Values.infra.redisHost (printf "%s-redis" .Release.Name) .Values.infra.external) (int .Values.redis.port) | b64enc | quote }}
